name: product-catalog-ci

on: 
  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to (dev, qa, prod)"
        required: true
        default: "dev"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go 1.22
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Build
      run: |
        cd src/product-catalog
        go mod download
        go build -o product-catalog-service main.go

    - name: Unit tests
      run: |
        cd src/product-catalog
        go test ./...

  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go 1.22
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.55.2
        run: golangci-lint run
        working-directory: src/product-catalog

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'
    environment: ${{ github.event.inputs.environment }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push to ECR
      uses: docker/build-push-action@v6
      with:
        context: src/product-catalog
        file: src/product-catalog/Dockerfile
        push: true
        tags: |
          ${{ steps.login-ecr.outputs.registry }}/product-catalog:${{ github.event.inputs.environment }}-${{ github.run_id }}
          ${{ steps.login-ecr.outputs.registry }}/product-catalog:latest
