name: product-catalog-cd

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment (dev, qa, prod)"
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod
      image_name:
        description: Image name
        required: true
      image_tag:
        description: Docker image tag to deploy
        required: true

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Update image tag in manifest
        run: |
          sed -i "s|image: .*|image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ inputs.image_tag }}|" kubernetes/productcatalog/deploy.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl rollout restart deployment/${{ inputs.image_name }}
          kubectl rollout status deployment/${{ inputs.image_name }}
